FROM node:16-alpine

RUN apk add --no-cache git

WORKDIR /usr/src/streets-gl

COPY ./streets-gl/package.json /usr/src/streets-gl
COPY ./streets-gl/package-lock.json /usr/src/streets-gl
RUN npm ci


COPY ./streets-gl /usr/src/streets-gl
RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "start" ]